export const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2021 - 2022 (1 Year)",
      title: "D4 Informatic Technology",
      desc: "- Success graduated with GPA 3.87",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2018 - 2021 (3 Years)",
      title: "D3 Informatic Management",
      desc: "- Success graduated with GPA 3.95 | Success make Finance Analyze App based on website for final exam",
    },
    {
      id: 3,
      category: "experience",
      icon: "icon-graduation",
      year: "Feb 2022 - Aug 2022",
      title: "Information Technology Support & Developer (PT Rapid Plast Indonesia)",
      desc: "Success maintenance test online application based on website (Maintenance about low read data to fast read data) | Building Attedance Application based on website and mobile | Success to help employees remain related to problems using applications such as Microsoft Excel and Microsoft Outlook | Success to maintenance PC and CPU office",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "Jan 2020 - Jul 2021",
      title: "Research Assistant (Politeknik Negeri Malang)",
      desc: "1. Success make application about calculating and finding the LCM (Least Common Multiple)\n2. Success checked research reports as needed",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "Jun 2020 - Jan 2021",
      title: "Software Developer (CV Candra Food)",
      desc: "Success building 3 applications in CV Candra Food | Maintenance of financial applications and warehouse applications of CV Candra Food",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "Jun 2020 - Agu 2020",
      title: "Web Developer (KPPN Kediri)",
      desc: "Success building 2 application for Proffesional Placement requirement",
    },
  ];