export const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2018 - 2021",
      title: "D3 Informatic Management",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2021 - 2022",
      title: "D4 Informatic Technology",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 3,
      category: "experience",
      icon: "icon-graduation",
      year: "2009 - 2013",
      title: "Honours Degree",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "2019 - present",
      title: "Web Designer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "2013 - 2017",
      title: "Front-End Developer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "2009 - 2013",
      title: "Back-End Developer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
  ];